/**
 * Raw native bindings (generated by NAPI-RS).
 *
 * Application code should import from the package root instead; this module
 * exists so the public layer has a single place that knows about the native
 * artifact layout.
 *
 * Note: deliberately named-export only — re-exporting a CommonJS module as
 * a default export is unreliable across Node ESM interop, Bun and bundlers.
 */
import native from '../index.js'

export { native }
